### ISSUE TITLE
Sink to Cosmos using MongoDB fails when global replication enabled

### ISSUE THREAD

**Issue by chadmott** [hpgrahsl/kafka-connect-mongodb#87] opened 2019-06-23 01:00 UTC
When Sinking to Azure Cosmos DB, everything works as expected when geo-redundancy is turned off. 

When you turn it on (multi read, single write), I see the following error:

```
Caused by: com.mongodb.MongoCommandException: Command failed with error 61: 'query in command must target a single shard key' on server <AZURESERVER>:10255. The full response is {"_t": "OKMongoResponse", "ok": 0, "code": 61, "errmsg": "query in command must target a single shard key", "$err": "query in command must target a single shard key"}
```

is there any way I can specify a shard key in this environment?

**Comment by hpgrahsl** [comment] 2019-06-24 19:10
hi @chadmott. so you seem to be one of the "cosmosdb customers" then :)
I quickly investigated this issue and from what I've seen it seems to be a flaw in the MongoDB API support by Azure CosmosDB. The problem is related to bulk writes that are used by the sink connector behind the scenes. My experiments using the mongo shell (so this is absolutely unrelated to the sink connector or the java driver) showed the following: 

Using the insertMany or bulkWrite-insertOne methods on collections work also with partitioned cosmosdb collections. The problem is related to using bulkWrite-replaceOne which is needed in order to successfully perform writes using upsert semantic -> this is what the sink connector uses and this is what CosmosDB MongoDB API has obviously its issues with.

That being said I currently cannot directly do anything about it. Maybe it's possible to find a workaround for this. What might work - depending on what your use case really needs - is that you only do insert-driven workloads i.e. do not rely on upsert semantics. Then the bulkWrites ideally succeed also for partitioned collections. What you would still need however is a custom write model using InsertOneModel instead of the ReplaceOneModel that is used currently. You can take a look at the [existing ones](https://github.com/hpgrahsl/kafka-connect-mongodb/tree/master/src/main/java/at/grahsl/kafka/connect/mongodb/writemodel/strategy) to get some inspiration - it's pretty straight-foward to implement this see also the [docs here](https://github.com/hpgrahsl/kafka-connect-mongodb#custom-write-models). **PRs welcome - just saying :)**

I hope this helps you at least to understand the problem. Happy to hear from you!

**Comment by chadmott** [comment] 2019-06-24 19:14
Thank you for the thoughtful reply... after some trial and error, I discovered the strangest thing...

If i _manually_ create a DB in a geo-redundant account, I must specify a shard key, and I get the error. 

However, If I just create the geo-redundant account, and create no DBs or Collections, and use the connector (or mongoDB console), Cosmos will provision one _without_ the previously required shard key, and things work like magic. 

I'm still investigating this, but it appears to solve the issue. So for others out there... give this a shot.

**Comment by hpgrahsl** [comment] 2019-06-24 19:41
Not sure if I fully get your response. But yes it's possible to rely on "auto-create" of collections. From what I've experienced in the past however is that you will always only get default settings for such collections e.g. 1000 RUs and limited storage capacity (10GB) meaning that these collections are not partitioned and in turn don't have sharding support. Thus I would assume that the ones provisioned in your case are not sharded, right? This would also make sense since non-sharded collections are supported without this "shard-key related" issue you were referring to in the first place.

**Comment by hpgrahsl** [comment] 2019-07-03 13:49
@chadmott could you verify if what I wrote above holds true? would be interested if something was changed in this regard. also we can maybe close this issue?

**Comment by hpgrahsl** [comment] 2019-07-11 18:03
I'm closing this now @chadmott. But feel free to reopen if needed. Thx.

**Closed by hpgrahsl** 2019-07-11 18:03 UTC
Labels: question
