### ISSUE TITLE
Update and Delete Operation for CDC Handler

### ISSUE THREAD

**Issue by azizimansyah** [hpgrahsl/kafka-connect-mongodb#8] opened 2017-10-02 07:10 UTC
Hi,

I've noticed that Debezium MongoDB has updated to version 0.6.0, and they have differentiated the _id field type in the key's payload, is it now possible for you to implement the "update" and "delete" operation for Debezium MongoDB CDC handler?

Thanks.

**Comment by hpgrahsl** [comment] 2017-10-02 15:39
Thx for your comment. In fact, I did this small but IMHO vital contribution for debezium 0.6 in order to be able to support all mongodb CDC events at the sink side :) so yes, as of now it is of course possible to integrate this into the sink connector code base. It's definitely on my todo list but I just didn't find the time yet to get it done. Maybe you can help with the implementation and contribute a PR?

**Comment by hpgrahsl** [comment] 2017-10-04 19:04
@azizimansyah FYI the implementation of update/delete CDC ops is almost finished. Afterwards, I'll have to write some tests as well. Will let you know when it's been merged into master...

**Comment by azizimansyah** [comment] 2017-10-05 08:53
Thanks for the fast response :)
I plan to use it for real-time mongodb replication from one cluster to another cluster. I think it is possible to implement it by using debezium as the source connector and your kafka connect mongodb as the sink connector. I'm looking forward to it!

**Comment by hpgrahsl** [comment] 2017-10-05 15:49
Hi,While you're right that this is one possible scenario you have to be aware that what you would replicate are all CRUD based change events 'only' happening in a db collection. This is not the same as a fully fledged MongoDb replication.If this is fine for you go ahead and give it a try. Feedback always welcome.On 5 Oct 2017 10:53, azizimansyah <notifications@github.com> wrote:Thanks for the fast response :)
I plan to use it for real-time mongodb replication from one cluster to another cluster. I think it is possible to implement it by using debezium as the source connector and your kafka connect mongodb as the sink connector. I'm looking forward to it!

**Comment by hpgrahsl** [comment] 2017-10-06 16:59
@azizimansyah Done see this PR https://github.com/hpgrahsl/kafka-connect-mongodb/pull/9
Let me know how it works out for you...

**Closed** 2017-10-06 16:59 UTC
Labels: enhancement

**Comment by azizimansyah** [comment] 2017-10-10 09:48
Thanks a lot, it works well for me. Awesome!

I have some questions to ask:
1. Does the connector support consuming multiple topic from kafka and produce to multiple collection to mongodb? so that instead of creating multiple connector for multiple topic, I could use only one connector for multiple topic.
2. What is the difference between `kafka-connect-mongodb-1.0-SNAPSHOT.jar` and `kafka-connect-mongodb-1.0-SNAPSHOT-jar-with-dependencies.jar` and which one should I use? I've tried both of them and they both work well.

I noticed there's a typo in your readme, I think `at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandlerHandler` should be replaced with `at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler`.

**Comment by hpgrahsl** [comment] 2017-10-10 18:14
@azizimansyah I'm glad to hear that it's useful for you and works well so far :)

w.r.t. your questions:

ad 1)

at the moment it is supporting only 1 topic per running connector. this restriction is to some degree by design. when you think about the normal scenario, you would consume from different topics which most of the time contain data exhibiting a totally different record structure. this would mean that one connector configuration would need to support all the available options for each and every topic since, for instance, the postprocessor chain itself and all contained postprocessors with its corresponding settings would vary most likely. while this would certainly be feasible to achieve, I decided against one big complex configuration across multiple topics. also mixing normal connector behaviour with the CDC operation mode is currently beyond the scope of my implementation.
a part from that, there is the configuration option to have AVRO or JSON message serialization. to my knowledge, this settings can only be configured once per connector - not on a topic level. this would be a case where you would have to run more than one connector anyway.

but for scenarios like yours, where one would want to run CDC operation mode for multiple topics I understand that it would be much more comfortable and also not that resource intensive to have several connectors running. that being said, I'll probably find some time to take a look how to get this integrated without too much effort at least for the CDC scenario.

ad 2) 
they contain the same connector implementation code. the difference being that the *-with-dependencies.jar, as the name suggests, is a self-contained jar file with all the mongodb-specific libraries that are needed. so in case you have all the needed jars separately available on your classpath also the other jar will work fine. if not, you would end up with e.g. ClassNotFoundExecptions.
