### ISSUE TITLE
Issue with CDC Sink Connector from Debezium MongoDB Connector

### ISSUE THREAD

**Issue by kalbmj** [hpgrahsl/kafka-connect-mongodb#11] opened 2017-12-06 22:18 UTC
Using the example for Change Data Capture Mode from the README, we are seeing an issue that throws an unrecoverable exception right after the connector config is posted. 
Connector def posted below:
![image](https://user-images.githubusercontent.com/10438017/33688434-f8872cd0-daa0-11e7-933a-7ecb15c9dc7d.png)

And error thrown posted below:
![image](https://user-images.githubusercontent.com/10438017/33689032-6a131380-daa3-11e7-9a34-e47973436302.png)

The collection exists in mongo and mongo is reachable from kafka connect. The confluent schema registry is running and is reachable from kafka connect. Also, other kafka streams applications are able to deserialize these debezium-generated avro messages fine from the same topic the failing connector is reading from. Please let us know if you need any more information to help us solve. Thank you.

**Comment by hpgrahsl** [comment] 2017-12-07 07:45
@kalbmj thx for reaching out. I'm happy to see that you try to make use of the mongodb cdc handler. 
what you report is an unfortunate regression bug which most likely happened due to one of my recent refactorings. luckily it will be easy to get rid of the error :) I'll provide a fix as well as a test case which reproduces and addresses this issue as soon as I find some time, most probably later today.

**Comment by kalbmj** [comment] 2017-12-07 14:56
Thank you for looking into this. Another related question, do you have (or have you seen) any use case examples for CDC from MongoDB to MySQL?

**Comment by kalbmj** [comment] 2017-12-07 15:58
MongoDBHandler is extending DebeziumCDCHandler but they are both maintaining their own operations map.    DebeziumCDCHandler never sets it operations map with values, but that is where the getCdcOperation is at
So we added 
    public DebeziumCdcHandler(MongoDbSinkConnectorConfig config) {
        super(config);
        logger.info("DebeziumCdcHandler contructor config {}",config.toString());
        operations.put(OperationType.CREATE,new MongoDbInsert());
        operations.put(OperationType.READ,new MongoDbInsert());
        operations.put(OperationType.UPDATE,new MongoDbUpdate());
        operations.put(OperationType.DELETE,new MongoDbDelete());
        
        logger.info("DebeziumCdcHandler operations map {}",operations);
        logger.info("DebeziumCdcHandler operations map size {}",operations.size());
    } 
Now working

**Comment by hpgrahsl** [comment] 2017-12-07 17:49
while this indeed works it's not good way to leave it like this :) I'm currently working on a fix together with an additional test. as soon as it it merged I'll let you know and you might want to use the new version instead.

**Comment by hpgrahsl** [comment] 2017-12-07 18:42
@kalbmj fixed -> see https://github.com/hpgrahsl/kafka-connect-mongodb/pull/12
have fun!

**Closed** 2017-12-11 17:09 UTC
Labels: bug
