### ISSUE TITLE
mongodb.delete.on.null.values not working

### ISSUE THREAD

**Issue by lmcsegura** [hpgrahsl/kafka-connect-mongodb#59] opened 2018-11-02 16:39 UTC
Hi ,

Thanks in advance for your help.

I'm using your connector 1.2 (latest version) which works for me "Insert" and "Update" as stated in your documentation. But, unfortunately I cannot get the document "Deletion" in MongoDB to work.

My configuration:
`
{
  "name": "mongodb-sink-dds",
  "config": {
...

    "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": false,
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "mongodb.field.renamer.regexp": "[]",
    "mongodb.max.batch.size": "0",
    "mongodb.max.num.retries": "3",
    "mongodb.change.data.capture.handler": "",
    "tasks.max": "1",
    "mongodb.connection.uri": "mongodb://192.168.59.101:27017/kafkaconnect?w=1&journal=true",
    "topics": "ot1",
    "mongodb.field.renamer.mapping": "[]",
    "mongodb.writemodel.strategy": "at.grahsl.kafka.connect.mongodb.writemodel.strategy.UpdateOneTimestampsStrategy",
    "mongodb.post.processor.chain": "at.grahsl.kafka.connect.mongodb.processor.DocumentIdAdder",
    "mongodb.delete.on.null.values": true,
    "mongodb.document.id.strategies": "",
    "mongodb.value.projection.type": "none",
    "mongodb.value.projection.list": "",
    "mongodb.key.projection.type": "none",
    "mongodb.key.projection.list": "",
    "name": "mongodb-sink-dds",
    "mongodb.collection": "kafkatopicdds",
    "mongodb.document.id.strategy": "at.grahsl.kafka.connect.mongodb.processor.id.strategy.ProvidedInKeyStrategy",
    "mongodb.retries.defer.timeout": "5000"
  }
}
`

Now,
Assume the following record in MongoDB:
`{

    "_id": NumberLong("1"),
    "name": "JohnDoe",
    "address": "some address",
    "_insertedTS": ISODate("2018-10-30T12:29:11.095Z"),
    "_modifiedTS": ISODate("2018-10-30T12:29:11.095Z")

}
`

Nevertheless,
The following messages have been sent to Kafka using Kafka-Streams to delete such record with no success:

Will do nothing, will not delete the record in mongodb
`{"_id":1}      null`

Will set name and address to null but not delete the document in MongoDB
`{"_id":1}      {"_id":null,"name":null,"address":null}`

I'm trying to understand your statement:
_"The idea is that the sink connector will try to delete a mongodb document from the collection iff the **whole value struct is null**"_
from here: 
[https://github.com/hpgrahsl/kafka-connect-mongodb/issues/47](url)

Also,
_For these cases the sink connector can be configured to delete records in MongoDB whenever it encounters sink records which exhibit null values_
from here:
[https://github.com/hpgrahsl/kafka-connect-mongodb#convention-based-deletion-on-null-values](url)

Obviously, I'm somehow using your connector incorrectly.

Could you please clarify what you mean by deleting the record in MongoDB using convention?
Could you please indicate in your document an example message of what to sent into Kafka which would delete a document?

Many Thanks,

Kind Regards,
Luis

**Comment by hpgrahsl** [comment] 2018-11-03 07:35
Hi @lmcsegura,

Thx for reporting this. I'm afraid you're indeed facing nasty a bug here. I already identified the problem. Will provide a fix as soon as I find some time.

Until then, kind regards!

**Comment by lmcsegura** [comment] 2018-11-03 16:41
Hi @hpgrahsl,

Thank you for your prompt response. Look forward to hear from you.

Regards,
Luis.

**Comment by hpgrahsl** [comment] 2018-11-04 14:12
@lmcsegura you can checkout the issue-59 branch and build this SNAPSHOT version which contains a fix. let me know if it works for you. I'll probably add a few more test cases before merging it later. next release will contain the fix for sure.

**Comment by lmcsegura** [comment] 2018-11-06 12:42
Hi hpgrashl,

Thanks for providing a fix branch. Took me a bit more time to test as I wanted to be a bit more thorough and reply to you with as much detail as I can.

I’ve used version 1.2.1 from branch59 after compilation: “kafka-connect-mongodb-1.2.1-SNAPSHOT-jar-with-dependencies.jar”
I’m also using the same previous configuration:


**My test results:**

1) YES. It now deletes/removes the record/document completely from MongoDB.

If I have a document in MongoDB such as:
`{

  "_id": NumberLong("1"),
  "name": "JohnDoe",
  "address": "some address",
  "_insertedTS": ISODate("2018-10-30T12:29:11.095Z"),
  "_modifiedTS": ISODate("2018-10-30T12:29:11.095Z")
}`


Sending the following kafka message:
`{"_id":1} null`
Will completely remove the document from MongoDB as stated per your comment:
_"The idea is that the sink connector will try to delete a mongodb document from the collection iff the whole value struct is null"_
from here:
[https://github.com/hpgrahsl/kafka-connect-mongodb/issues/47](url)


2) Insert and Update cases (tested before) still working as before.


3) Continued my testing and I’m **now facing another problem**.
Don’t know if it is related with the fix, or if it is a bug or simply works as intended by you. Maybe you can clarify.

Decided to improve my record structure.
`{

"_id": NumberLong("1"),
"name": "JohnDoe",
"address": "some address",
"_insertedTS": ISODate("2018-10-30T12:29:11.095Z"),
"_modifiedTS": ISODate("2018-10-30T12:29:11.095Z")
}`

Adding a “profile” substructure by sending the following message to kafka.
`{"_id":1} {“profile”: {“status”:”A”, “comments”:”bla”}}`

Which now reflects in MongoDB like:
`{

"_id": NumberLong("1"),
"name": "JohnDoe",
"address": "some address",
"_insertedTS": ISODate("2018-10-30T12:29:11.095Z"),
"_modifiedTS": ISODate("2018-10-30T12:29:11.095Z")
“profile”: {
  “status” : “A”
  “comments” : “bla”
}
}`

I would like to be able to delete/erase/… the profile substructure. For that I send the following message to kafka:
`{"_id":1} {“profile”:null}`

Which then has the obvious following effect.
`{

"_id": NumberLong("1"),
"name": "JohnDoe",
"address": "some address",
"_insertedTS": ISODate("2018-10-30T12:29:11.095Z"),
"_modifiedTS": ISODate("2018-10-30T12:29:11.095Z")
“profile”: null
}`

So far so good. 

BUT,
To re-instate the profile, by sending the exact same “adding profile” message which worked before
`{"_id":1} {“profile”: {“status”:”A”, “comments”:”bla”}}`

I would expect the same past state:
`{

"_id": NumberLong("1"),
"name": "JohnDoe",
"address": "some address",
"_insertedTS": ISODate("2018-10-30T12:29:11.095Z"),
"_modifiedTS": ISODate("2018-10-30T12:29:11.095Z")
“profile”: {
  “status” : “A”
  “comments” : “bla”
}
}`

**Unfortunately, I get the following error from the connector:**
`
[2018-11-04 02:10:48,271] ERROR error on mongodb operation (at.grahsl.kafka.connect.mongodb.MongoDbSinkTask:138)
com.mongodb.MongoBulkWriteException: Bulk write operation error on server 192.168.59.101:27017. Write errors: [BulkWriteError{index=0, code=28, message='Cannot create field 'COMMENTS' in element {profile: "null"}', details={ }}].        
        at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:176)                                                                                                                                           
        at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:205)                                                                                                                                       
        at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:146)                                                                                                                                          
        at com.mongodb.operation.BulkWriteBatch.getResult(BulkWriteBatch.java:227)                                                                                                                                                           
        at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:276)
        at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:67)                                                                                                                                         
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:200)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:191)
        at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:424)                                                                                                                                          
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:191)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:67)                                                                                                                                            
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193)                                                                                                                   
        at com.mongodb.client.internal.MongoCollectionImpl.executeBulkWrite(MongoCollectionImpl.java:467)
        at com.mongodb.client.internal.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:447)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.processSinkRecords(MongoDbSinkTask.java:126)                                                                                                                                      
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$null$0(MongoDbSinkTask.java:110)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$put$1(MongoDbSinkTask.java:109)                                                                                                                                            
        at java.util.HashMap.forEach(HashMap.java:1289)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:108)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`


Do you have some idea(s) about this error?

(If I would go directly to MongoDB, I would be able to “upsert” the profile again, even when is currently null)


Many Thanks for your efforts,

Kind Regards,
Luis.

**Comment by hpgrahsl** [comment] 2018-11-13 16:54
> Sorry for my late response. Some things at work took high priority and was not able to pursue immediately your response.

No worries.
 
> Thanks for taking the time to clarify, help and of course your great work ! :)

THX. You're welcome. I'm happy to help!

> I read your comments and have re-tested and you're absolutely correct.
> The sequence
> 
> {"_id":1} {"name": "JohnDoe","address": "some address"}
> {"_id":1} {"profile": {"status":"A", "comments":"bla"}}
> {"_id":1} {"profile": null}
> {"_id":1} {"profile": {"status":"A", "comments":"bla"}}
> 
> Works correctly using:
> `"at.grahsl.kafka.connect.mongodb.writemodel.strategy.UpdateOneTimestampsStrategy"`

Good to hear it's now also working for you :)

> In conclusion,
> Using your branch-59, I'm now able to _insert_, _update_ and _delete_ as expected and per your documentation.
> 
> **Will you make this fix available to the normal branch afterwards?**

Definitely yes. It will be part of the next release (either minor i.e. v1.3.0 or patch v1.2.1)

> Have one last comment about the delete when using "mongodb.delete.on.null.values = true"
> 
> So, in branch-59 you have provided a fix, so that the record (main document) is actually deleted from MongoDB as stated per documentation.
> 
> But, when passing "null" for a subdocument:
> `{"_id":1} {"profile": null}`
> 
> The subdocument in MongoDB does not get deleted, but rather is set to null.

Exactly this is the expected behaviour. Again, this deletion by convention approach on Kafka SinkRecord values being null is supposed to delete the complete MongoDB document - never only parts of it. Thus setting a sub-document to null is the most natural approach to deal with this.

> For consistency, shouldn't subdocument(s) be also removed from MongoDB if null is passed and "mongodb.delete.on.null.values = true" ?

No - like I said above it would be a completely different semantic to remove the full sub-document. Besides, the chosen WriteModelStrategy simply cannot do what you suggest, since it always performs an UpdateOneModel under the covers which means all you can do is use valid MongoDB update operations on the document matched by the filter. Thus if you "set" the "profile" sub-document to null it will never be removed from the document structure.

**Closed by hpgrahsl** 2018-11-13 16:54 UTC
Labels: bug
